// <auto-generated />
using System;
using Database.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Database.Migrations
{
    [DbContext(typeof(MasterContext))]
    [Migration("20211114094214_008")]
    partial class _008
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "Cyrillic_General_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Database.Models.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("Brands_pk")
                        .IsClustered(false);

                    b.ToTable("Brands", "PhoneShop");
                });

            modelBuilder.Entity("Database.Models.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Amount")
                        .HasColumnType("int")
                        .HasColumnName("amount");

                    b.Property<int?>("PhoneId")
                        .HasColumnType("int")
                        .HasColumnName("phoneId");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("userId");

                    b.HasKey("Id")
                        .HasName("Cart_pk")
                        .IsClustered(false);

                    b.HasIndex("PhoneId");

                    b.HasIndex("UserId");

                    b.ToTable("Carts", "PhoneShop");
                });

            modelBuilder.Entity("Database.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comments")
                        .HasMaxLength(3000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(3000)")
                        .HasColumnName("comments");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("createTime");

                    b.Property<string>("PhoneSlug")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("phoneSlug");

                    b.Property<int?>("Rating")
                        .HasColumnType("int")
                        .HasColumnName("rating");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("userId");

                    b.HasKey("Id")
                        .HasName("Comments_pk")
                        .IsClustered(false);

                    b.HasIndex("UserId");

                    b.ToTable("Comments", "PhoneShop");
                });

            modelBuilder.Entity("Database.Models.Phone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BrandSlug")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("brandSlug");

                    b.Property<string>("Dimension")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("dimension");

                    b.Property<bool?>("Hided")
                        .HasColumnType("bit")
                        .HasColumnName("hided");

                    b.Property<string>("Images")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("images");

                    b.Property<string>("Os")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("os");

                    b.Property<string>("PhoneName")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("phoneName");

                    b.Property<string>("PhoneSlug")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("phoneSlug");

                    b.Property<int?>("Price")
                        .HasColumnType("int")
                        .HasColumnName("price");

                    b.Property<string>("ReleaseDate")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("release_date");

                    b.Property<string>("Specifications")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("specifications");

                    b.Property<int?>("Stock")
                        .HasColumnType("int")
                        .HasColumnName("stock");

                    b.Property<string>("Storage")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("storage");

                    b.Property<string>("Thumbnail")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("thumbnail");

                    b.HasKey("Id")
                        .HasName("Phones_pk")
                        .IsClustered(false);

                    b.ToTable("Phones", "PhoneShop");
                });

            modelBuilder.Entity("Database.Models.PriceSubscriber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BrandSlug")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("brandSlug");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("email");

                    b.Property<string>("PhoneSlug")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("phoneSlug");

                    b.HasKey("Id")
                        .HasName("PriceSubscribers_pk")
                        .IsClustered(false);

                    b.ToTable("PriceSubscribers", "PhoneShop");
                });

            modelBuilder.Entity("Database.Models.PromoCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Amount")
                        .HasColumnType("int")
                        .HasColumnName("amount");

                    b.Property<int?>("Discount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("discount")
                        .HasDefaultValueSql("((0))");

                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("key");

                    b.Property<int?>("PhoneId")
                        .HasColumnType("int")
                        .HasColumnName("phoneId");

                    b.HasKey("Id")
                        .HasName("PromoCodes_pk")
                        .IsClustered(false);

                    b.HasIndex("PhoneId");

                    b.ToTable("PromoCodes", "PhoneShop");
                });

            modelBuilder.Entity("Database.Models.StockSubscriber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BrandSlug")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("brandSlug");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("email");

                    b.Property<string>("PhoneSlug")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("phoneSlug");

                    b.HasKey("Id")
                        .HasName("StockSubscribers_pk")
                        .IsClustered(false);

                    b.ToTable("StockSubscribers", "PhoneShop");
                });

            modelBuilder.Entity("Database.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("password");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("role");

                    b.HasKey("Id")
                        .HasName("Users_pk")
                        .IsClustered(false);

                    b.HasIndex(new[] { "Email" }, "Users_email_uindex")
                        .IsUnique();

                    b.ToTable("Users", "PhoneShop");
                });

            modelBuilder.Entity("Database.Models.WishList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("PhoneId")
                        .HasColumnType("int")
                        .HasColumnName("phoneId");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("userId");

                    b.HasKey("Id")
                        .HasName("WishList_pk")
                        .IsClustered(false);

                    b.HasIndex("PhoneId");

                    b.HasIndex("UserId");

                    b.ToTable("WishList", "PhoneShop");
                });

            modelBuilder.Entity("Database.Models.Cart", b =>
                {
                    b.HasOne("Database.Models.Phone", "Phone")
                        .WithMany("Carts")
                        .HasForeignKey("PhoneId")
                        .HasConstraintName("Carts_Phones_id_fk");

                    b.HasOne("Database.Models.User", "User")
                        .WithMany("Carts")
                        .HasForeignKey("UserId")
                        .HasConstraintName("Carts_Users_id_fk");

                    b.Navigation("Phone");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Database.Models.Comment", b =>
                {
                    b.HasOne("Database.Models.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .HasConstraintName("Comments_Users_id_fk");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Database.Models.PromoCode", b =>
                {
                    b.HasOne("Database.Models.Phone", "Phone")
                        .WithMany("PromoCodes")
                        .HasForeignKey("PhoneId")
                        .HasConstraintName("PromoCodes_Phones_id_fk");

                    b.Navigation("Phone");
                });

            modelBuilder.Entity("Database.Models.WishList", b =>
                {
                    b.HasOne("Database.Models.Phone", "Phone")
                        .WithMany("WishLists")
                        .HasForeignKey("PhoneId")
                        .HasConstraintName("WishList_Phones_id_fk");

                    b.HasOne("Database.Models.User", "User")
                        .WithMany("WishLists")
                        .HasForeignKey("UserId")
                        .HasConstraintName("WishList_Users_id_fk");

                    b.Navigation("Phone");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Database.Models.Phone", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("PromoCodes");

                    b.Navigation("WishLists");
                });

            modelBuilder.Entity("Database.Models.User", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("Comments");

                    b.Navigation("WishLists");
                });
#pragma warning restore 612, 618
        }
    }
}
